apiVersion: v1
kind: Service
metadata:
  name: self-healing-rag
spec:
  selector:
    app: self-healing-rag
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
  type: {{ .Values.service.type }}
